# Generated by Django 5.2.11 on 2026-03-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
